// Confirmed payment regression tests: real service/UI, versioned in-memory Firebase only.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
const root=path.join(__dirname,'../..'),read=name=>fs.readFileSync(path.join(root,name),'utf8');
const core=read('01-core.js'),source=read('09-posture-kb-invites-private.js'),authSource=core.slice(core.indexOf('function assignmentSession(){'),core.indexOf('// Retry bookkeeping',core.indexOf('function assignmentSession(){')));
const uiSource=source.slice(source.indexOf('var packagePaidUiStates='),source.indexOf('function requestPayment',source.indexOf('var packagePaidUiStates=')));
const clone=v=>JSON.parse(JSON.stringify(v));
function fixture(shared){
 const data=shared?shared.data:new Map(),versions=shared?shared.versions:new Map(),pending=[],writes=[],events=[],notices=[],unexpected=[],refresh=[],warnings=[];
 const body={firstElementChild:{view:'a'}};
 const c={console:{warn:(...args)=>warnings.push(args),log:console.log},crypto:webcrypto,Date,Map,Set,Promise,Uint8Array,setTimeout,clearTimeout,_db:{},_uid:'owner',tenantSessionGeneration:1,_tenantDataReady:true,CL:[{id:'a',_fbId:'client-a',trainerId:'owner',name:'Alfa',status:'active'},{id:'b',trainerId:'owner',name:'Beta',status:'active'}],PACKAGES:[{id:'p-a',_fbId:'package-a',trainerId:'owner',clientId:'a',clientName:'Alfa',title:'Pakiet',price:100.5,sessions:10,sessionsUsed:2,payStatus:'pending',invoiceDocId:'invoice-a',invoiceId:'INV-S-1'}],INVOICES:[{id:'invoice-a',trainerId:'owner',pkgId:'p-a',clientId:'a',nr:'INV-S-1',amount:100.5,status:'pending'}],cpClientId:'a',cpTab:'payments',allPackages:()=>c.PACKAGES,escHtml:s=>String(s||''),notify:m=>notices.push(m),fireIntEvent:(type,payload)=>{events.push({type,payload});return c.eventMode==='reject'?Promise.reject(Error('integration offline')):Promise.resolve();},renderPayPackages:()=>refresh.push('packages'),renderPayOverview:()=>refresh.push('overview'),renderPayInvoices:()=>refresh.push('invoices'),renderCPPayments:client=>refresh.push('client:'+client.id),refreshPaySurfaces:()=>refresh.push('surfaces'),document:{getElementById:id=>id==='cp-body'?body:null,querySelectorAll:()=>[]},_doc:(_db,col,id)=>({col,id}),_col:(_db,col)=>col,_where:(key,_op,val)=>({key,val}),_query:(col,...filters)=>({col,filters})};c.window=c;
 for(const name of ['persistById','requestPayment','pushMsg','_setDoc'])c[name]=()=>{unexpected.push(name);throw Error('Unexpected '+name);};
 if(!data.size){for(const client of c.CL)data.set('clients/'+(client._fbId||client.id),clone(client));data.set('packages/package-a',clone(c.PACKAGES[0]));data.set('invoices/invoice-a',clone(c.INVOICES[0]));}
 c._getDocsFromServer=async q=>{const result={docs:[...data].filter(([key,value])=>key.startsWith(q.col+'/')&&q.filters.every(f=>value[f.key]===f.val)).map(([key,value])=>{const snapshot=clone(value);return {id:key.split('/')[1],data:()=>clone(snapshot)};})};if(c.afterQuery)c.afterQuery(q);return result;};
 c.conflicts=0;c.commits=0;
 c._runTransaction=async(_db,fn)=>{for(let attempt=0;attempt<5;attempt++){
  const patches=[],reads=new Map();writes.push(patches);
  const result=await fn({get:async ref=>{const key=ref.col+'/'+ref.id,value=data.get(key);reads.set(key,versions.get(key)||0);const snapshot=value&&clone(value);return {exists:()=>!!snapshot,data:()=>clone(snapshot)};},update:(ref,patch)=>{if(c.mode==='secondfail'&&patches.length)throw Error('second update rejected');patches.push([ref.col+'/'+ref.id,clone(patch)]);}});
  if(c.mode==='null')return null;if(c.mode==='fail')throw Error('offline');
  if(c.mode==='defer')await new Promise((resolve,reject)=>pending.push({resolve,reject}));
  if([...reads].some(([key,version])=>(versions.get(key)||0)!==version)){c.conflicts++;continue;}
  patches.forEach(([key,patch])=>{data.set(key,{...data.get(key),...patch});versions.set(key,(versions.get(key)||0)+1);});if(patches.length)c.commits++;
  if(c.mode==='lost'&&patches.length)throw Error('lost ACK');return result;
 }throw Error('contention');};
 vm.createContext(c);vm.runInContext(authSource,c);vm.runInContext(read('package-save.js'),c);vm.runInContext(uiSource,c);
 return {c,data,versions,pending,writes,events,notices,unexpected,refresh,warnings,body};
}
async function tick(){for(let i=0;i<30;i++)await Promise.resolve();}
async function main(){
 let f=fixture();f.c.mode='defer';const one=f.c.markPaid('p-a'),two=f.c.markPaid('p-a');assert.equal(one,two);await tick();assert.equal(f.pending.length,1);assert.equal(f.c.PACKAGES[0].payStatus,'pending');assert.equal(f.c.INVOICES[0].status,'pending');assert.equal(f.events.length,0);assert.equal(f.notices.length,0);assert.equal(f.writes[0].length,2);
 f.c.PACKAGES[0].sessionsUsed=7;f.data.get('packages/package-a').sessionsUsed=7;f.pending.shift().resolve();const saved=await one;assert.equal(saved.transitioned,true);assert.equal(f.c.PACKAGES[0].payStatus,'paid');assert.equal(f.c.PACKAGES[0].sessionsUsed,7);assert.equal(f.data.get('packages/package-a').sessionsUsed,7);assert.equal(f.c.INVOICES[0].status,'paid');assert.equal(f.events.length,1);assert.equal(f.notices.length,1);assert.ok(f.refresh.includes('client:a'));assert.deepEqual(Object.keys(f.writes[0][0][1]).sort(),['payStatus','paymentWriteId']);assert.deepEqual(Object.keys(f.writes[0][1][1]).sort(),['paymentWriteId','status']);f.c.mode='ok';await f.c.markPaid('p-a');assert.equal(f.events.length,1);assert.equal(f.notices.length,1);assert.equal(f.c.commits,1);
 for(const mode of ['fail','null','secondfail']){f=fixture();f.c.mode=mode;await f.c.markPaid('p-a');assert.equal(f.c.PACKAGES[0].payStatus,'pending');assert.equal(f.data.get('packages/package-a').payStatus,'pending');assert.equal(f.data.get('invoices/invoice-a').status,'pending');assert.equal(f.c.commits,0);assert.equal(f.events.length,0);assert.ok(f.c.packagePaidUiStates.get('p-a').error);f.c.mode='ok';await f.c.markPaid('p-a');assert.equal(f.c.PACKAGES[0].payStatus,'paid');assert.equal(f.events.length,1);}
 f=fixture();f.c.mode='lost';await f.c.markPaid('p-a');assert.equal(f.data.get('packages/package-a').payStatus,'paid');assert.equal(f.c.PACKAGES[0].payStatus,'pending');assert.equal(f.events.length,0);assert.equal(f.c.packagePaymentConfirmedRecord({...f.data.get('packages/package-a'),sessionsUsed:8},'packages').payStatus,'pending');assert.equal(f.c.packagePaymentConfirmedRecord({...f.data.get('packages/package-a'),sessionsUsed:8},'packages').sessionsUsed,8);assert.equal(f.c.packagePaymentConfirmedRecord({...f.data.get('invoices/invoice-a'),_fbId:'invoice-a'},'invoices').status,'pending');f.c.mode='ok';const recovered=await f.c.markPaid('p-a');assert.equal(recovered.transitioned,true);assert.equal(f.events.length,1);assert.equal(f.c.commits,1);assert.equal(f.c.packagePaymentConfirmedRecord(f.data.get('packages/package-a'),'packages').payStatus,'paid');await f.c.markPaid('p-a');assert.equal(f.events.length,1);
 f=fixture();f.data.get('packages/package-a').payStatus='paid';f.data.get('invoices/invoice-a').status='paid';await f.c.markPaid('p-a');assert.equal(f.c.PACKAGES[0].payStatus,'paid');assert.equal(f.c.commits,0);assert.equal(f.events.length,0);
 f=fixture();f.data.get('packages/package-a').payStatus='paid';await f.c.markPaid('p-a');assert.equal(f.data.get('invoices/invoice-a').status,'paid');assert.equal(f.events.length,0);assert.equal(f.writes[0].length,1);
 for(const mutate of [f=>f.c.CL[0].trainerId='other',f=>f.c.CL[0].archived=true,f=>f.data.get('clients/client-a').archived=true,f=>f.data.get('packages/package-a').trainerId='other',f=>f.data.get('packages/package-a').clientId='b',f=>f.data.get('invoices/invoice-a').trainerId='other',f=>f.data.get('invoices/invoice-a').clientId='b',f=>f.data.get('invoices/invoice-a').pkgId='other',f=>f.data.delete('invoices/invoice-a'),f=>f.data.delete('packages/package-a')]){f=fixture();mutate(f);await f.c.markPaid('p-a');assert.equal(f.c.PACKAGES[0].payStatus,'pending');assert.equal(f.c.commits,0);assert.equal(f.events.length,0);}
 // Legacy nr/id lookups are owner-scoped and accepted only with an unambiguous client/link.
 for(const legacy of ['pkgId','id','nr','uuid-no-pkgId']){f=fixture();const pkg=f.data.get('packages/package-a'),invoice=f.data.get('invoices/invoice-a');if(legacy!=='uuid-no-pkgId'){delete pkg.invoiceDocId;delete f.c.PACKAGES[0].invoiceDocId;}if(legacy!=='pkgId')delete invoice.pkgId;if(legacy==='id'){pkg.invoiceId=invoice.id;f.c.PACKAGES[0].invoiceId=invoice.id;}await f.c.markPaid('p-a');assert.equal(f.c.PACKAGES[0].payStatus,'paid');assert.equal(f.events.length,1);}
 for(const invalid of ['ambiguous','no-link','no-client','conflicting-link']){f=fixture();delete f.c.PACKAGES[0].invoiceDocId;delete f.data.get('packages/package-a').invoiceDocId;const invoice=f.data.get('invoices/invoice-a');delete invoice.pkgId;if(invalid==='ambiguous')f.data.set('invoices/second',{...invoice,id:'second'});if(invalid==='no-link')invoice.nr='other';if(invalid==='no-client')delete invoice.clientId;if(invalid==='conflicting-link')invoice.pkgId='other';await f.c.markPaid('p-a');assert.equal(f.c.commits,0);assert.equal(f.events.length,0);}
 f=fixture();delete f.c.PACKAGES[0].invoiceDocId;delete f.data.get('packages/package-a').invoiceDocId;delete f.data.get('invoices/invoice-a').pkgId;f.data.set('invoices/foreign',{id:'foreign',trainerId:'other',clientId:'a',nr:'INV-S-1',status:'pending'});await f.c.markPaid('p-a');assert.equal(f.c.commits,1);assert.equal(f.data.get('invoices/foreign').status,'pending');
 f=fixture();delete f.c.PACKAGES[0].invoiceDocId;delete f.data.get('packages/package-a').invoiceDocId;delete f.data.get('invoices/invoice-a').pkgId;f.c.afterQuery=q=>{if(q.filters.some(x=>x.key==='nr'))f.data.get('invoices/invoice-a').nr='different';};await f.c.markPaid('p-a');assert.equal(f.c.commits,0);assert.equal(f.c.PACKAGES[0].payStatus,'pending');assert.equal(f.events.length,0);
 for(const late of ['logout','archive','other-client','other-tab','reopen']){f=fixture();f.c.mode='defer';const promise=f.c.markPaid('p-a');await tick();if(late==='logout'){f.c.tenantSessionGeneration++;f.c.clearPackagePaidUiStates();}if(late==='archive')f.c.CL[0].archived=true;if(late==='other-client')f.c.cpClientId='b';if(late==='other-tab')f.c.cpTab='overview';if(late==='reopen')f.body.firstElementChild={view:'reopened'};f.pending.shift().resolve();await promise;if(['logout','archive'].includes(late)){assert.equal(f.c.PACKAGES[0].payStatus,'pending');assert.equal(f.events.length,0);assert.equal(f.notices.length,0);}else{assert.equal(f.c.PACKAGES[0].payStatus,'paid');assert.equal(f.events.length,1);}assert.equal(f.refresh.includes('client:a'),false);}
 const shared={data:new Map(),versions:new Map()},left=fixture(shared),right=fixture(shared);const concurrent=await Promise.all([left.c.markPaid('p-a'),right.c.markPaid('p-a')]);assert.equal(left.c.conflicts+right.c.conflicts,1);assert.equal(left.c.commits+right.c.commits,1);assert.equal(left.events.length+right.events.length,1);assert.equal(concurrent.filter(r=>r.transitioned).length,1);
 f=fixture();f.c.INVOICES=null;f.c.eventMode='reject';await f.c.markPaid('p-a');await tick();assert.equal(f.c.PACKAGES[0].payStatus,'paid');assert.equal(f.c.INVOICES[0].status,'paid');assert.equal(f.notices.length,1);assert.equal(f.c.packagePaidUiStates.has('p-a'),false);assert.ok(f.warnings.length);
 assert.ok(read('index.html').includes('packagePaymentConfirmedRecord(row,name)'));assert.ok(uiSource.includes('markPaid(this.dataset.packagePaid)'));assert.deepEqual(f.unexpected,[]);
 console.log('All confirmed package payment VM tests passed');
}
let watchdog;
const timeout=new Promise((_,reject)=>{watchdog=setTimeout(()=>reject(Error('Confirmed payment test timed out')),10000);});
Promise.race([main(),timeout]).catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>clearTimeout(watchdog));
